// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcz5bdepgfhuMGXqpNouvhUj_uk0W_RPY',
    appId: '1:1028541834869:web:03db8480621ee8f007fa3c',
    messagingSenderId: '1028541834869',
    projectId: 'safeflix',
    authDomain: 'safeflix.firebaseapp.com',
    storageBucket: 'safeflix.appspot.com',
    measurementId: 'G-5DQKLRSV2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5hoa1BRdVed2Ic_gLp7gR3sNto0udSE8',
    appId: '1:1028541834869:android:96901e27bf9a8f8407fa3c',
    messagingSenderId: '1028541834869',
    projectId: 'safeflix',
    storageBucket: 'safeflix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GKw05WAdJAlLLSUGpdz-7kaZZYbdF3I',
    appId: '1:1028541834869:ios:44e05379e29a420607fa3c',
    messagingSenderId: '1028541834869',
    projectId: 'safeflix',
    storageBucket: 'safeflix.appspot.com',
    iosBundleId: 'com.example.appMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GKw05WAdJAlLLSUGpdz-7kaZZYbdF3I',
    appId: '1:1028541834869:ios:35cb72ae025840fc07fa3c',
    messagingSenderId: '1028541834869',
    projectId: 'safeflix',
    storageBucket: 'safeflix.appspot.com',
    iosBundleId: 'com.example.appMovie.RunnerTests',
  );
}
